### ISSUE TITLE
Add an import option to allow not changing the Jellyfin icon and logo 

### ISSUE THREAD

**Issue by vaniilla9** [stpnwf/ZestyTheme#7]
**Describe the bug**
I love this theme, but I can’t use it as the default for my server as it hides all my custom Icons and logos to replace them with this themes white Jellyfin logos.

**To Reproduce**
If applicable, list the steps to reproduce the behavior:
1. Install this theme’s custom CSS.

**On a Smartphone or Tablet?**
 - Device:   ALL [e.g. iPhone 12, iPad Air, etc]

**Are you using any extra code in your "Custom CSS" field?**
Not at the moment. 

**Screenshots**
A picture is worth a thousand words...

![IMG_0078](https://github.com/user-attachments/assets/66a2c5cd-7805-40a0-9fb0-992c628fff95)

**Comment by stpnwf** [comment]
Glad to hear you are enjoying the theme.

 >...as it hides all my custom Icons and logos...

Ok, could you please clarify how are you trying to change them exactly? I only change the the Jellyfin logo, the icons are the default ones. So if you are having issues with the icons, it is prob not Zesty that is causing it.

Regarding the logo:
CSS will override code with its last occurrence. So for example, if you have a rule at the beginning of the code saying some element should be red, and another at the bottom saying it should be blue. CSS will only apply the last rule; so the element will be blue.

So if you are trying to change your Jellyfin logo through CSS (like I do in this theme), please try adding your CSS code **_after_** the Zesty import line in your Custom CSS field and let me know if that solves your issue. That way the CSS code will override the white logos with your own, rather than the other way around.

**Comment by vaniilla9** [comment]
Thank you for getting back! Yes, you are correct and I was mistaken - it is only that one Jellyfin logo. I wanted to avoid a CSS change, so I have manually overwritten the default Jellyfin logo and Icons with my own. If you wouldn’t mind, as you seem very knowledgeable in CSS, could you give me a CSS code to add to the end that would tell it to use its default logo path when you have time? Please and thank you

**Comment by vaniilla9** [comment]
I am sorry for closing and reopening the issue, I am very new to Github.

**Comment by stpnwf** [comment]
Sure, no worries. I am new myself :) 
I am on the run rn, but as soon as I get back I will send you the code to add.

**Comment by vaniilla9** [comment]
Awesome, you’re the best. Take your time - I am stuck at work anyways :)

**Comment by stpnwf** [comment]
I think this code will do it. It will use the default one. There is a dark version, but this one is default. Let me know if it doesn't.

```
.adminDrawerLogo img { content: url(/web/assets/img/banner-light.png) !important; } imgLogoIcon { content: url(/web/assets/img/banner-light.png) !important; } .pageTitleWithLogo { background-image: url(/web/assets/img/banner-light.png) !important; }
```
